---
# ansible-playbook -i inventories/sandbox/hosts -e target=Gulu --vault-password-file ../vault.key applyRole.yaml --become --become-method=sudo --become-user=root
#
#
- hosts: {{ target }}
  roles:
   - openvpn
